# version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mqtt-subscriber:
    build: ./mqtt_to_mongodb
    container_name: mqtt-subscriber
    depends_on:
      - mosquitto
      - mongodb
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongo-data:
